[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/iteria-key.pem
ansible_python_interpreter=/usr/bin/python3

[vault_servers]
vault1 ansible_host=184.72.195.43 vault_cluster_name=iteria-vault vault_ui_enabled=true

[webservers]
web1 ansible_host=184.72.195.43
web2 ansible_host=184.72.195.43

[app_servers]
app1 ansible_host=184.72.195.43

# Grupos por ambiente
[production:children]
vault_servers
webservers
app_servers

#[qa:children]
# Definir servidores de QA aquí

#[development:children]
# Definir servidores de desarrollo aquí